name: clayoven

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - ".mailmap"
      - ".rubocop.yml"
      - "assets/*"
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
          bundler-cache: true
      - name: Test and publish code coverage
        uses: paambaati/codeclimate-action@v8
        env:
          CC_TEST_REPORTER_ID: 6af7e3fd73fa4e4f354fc5da65ef7f77e908c47b01de069d7d718cdc4af4e6f0
        with:
          coverageCommand: bundle exec rake
