name: clayoven

on:
  push:
    branches: [master]
    paths-ignore:
      - "README.md"
      - ".gitignore"
      - ".mailmap"
      - ".rubocop.yml"
      - "assets/*"
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
          bundler-cache: true
